---
# tasks file for docker

- name: Task setup-Debian.yml
  include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Task setup-RedHat.yml
  include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'
